[build]
builder = "nixpacks"
coreThreads = 1

[deploy]
startCommant = "unicorn app.main:app -host 0.0.0.0 -port $PORT"
HealthcheckPath = "/api/health"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
