// Package models defines shared data types for the trading engine.
package models

import "time"

// Signal represents a trading signal generated by the AI strategy layer.
type Signal struct {
	Symbol     string    `json:"symbol"`
	Side       string    `json:"side"`       // BUY or SELL
	Quantity   float64   `json:"quantity"`
	Confidence float64   `json:"confidence"`
	StopLoss   float 'PUT',
    });
    if (res && res.ok) {
      const token = getAuthToken();
      if (token) loadData(token);
    }
  };

  const updateUserRole = async (userId: string, newRole: string) => {
    const res = await apiCall(`/api/v1/admin/users/${userId}/role?new_role=${encodeURIComponent(newRole)}`, {
      method: 'PUT',
    });
    if (res && res.ok) {
      const token = getAuthToken();
      if (token) loadData(token);
    }
  };

  const toggleUserActive = async (userId: string) => {
    const res = await apiCall(`/api/v1caller should have already updated it, but we track it here too)
        new_balance = self.account_balance + pnl

        # Update peak balance: only increase, never decrease
        if new_balance > self.peak_balance:
            self.peak_balance = new_balance

        # Drawdown = distance from historical peak to current balance
        if self.peak_balance > 0:
            self.current_drawdown_pct = ((self.peak_balance - new_balance) / self.64   `json:"stop_loss"`
	TakeProfit float64   `json:"take_profit"`
	Reasoning  string    `json:"reasoning"`
	CreatedAt  time.Time `json:"created_at"`
}

// Order represents a trade order in the execution pipeline.
type Order struct {
	ID         string    `json:"id"`
	Symbol     string    `json:"symbol"`
	Side       string    `json:"side"`       // BUY or SELL
	Type       string    `json:"type"`        // market, limit, stop
	Quantity   float64   `json:"quantity"`
	Price      float64   `json:"price,omitempty"`
	Status     string    `json/admin/users/${userId}/toggle-active`, {
      method: 'PUT',
    });
    if (res && res.ok) {
      const token = getAuthToken();
      if (token) loadData(token);
    }
  };

  // --- Auth gate: rely on backend verification, not localStorage ---
  if (authState === 'checking' || loading) {
    return (
      <div className="min-h-screen gradient-mesh grid-bg flex items-center justify-center px-6">
        <div className="glass-card p-8 max-w-md w-full text-center">peak_balance) * 100
            self.current_drawdown_pct = max(0, self.current_drawdown_pct)

        self.open_positions = max(0, self.open_positions - 1)